<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LongevityDiet.DietKnowledge.Application\LongevityDiet.DietKnowledge.Application.csproj" />
    <ProjectReference Include="..\LongevityDiet.DietKnowledge.Infrastructure\LongevityDiet.DietKnowledge.Infrastructure.csproj" />
  </ItemGroup>

</Project>
