// <auto-generated />
using System;
using LongevityDiet.Tracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LongevityDiet.Tracking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20261009123614_InitialTrackingSchema")]
    partial class InitialTrackingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LongevityDiet.Tracking.Domain.Entities.DailyTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("TrackingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TrackingDate")
                        .IsUnique();

                    b.ToTable("DailyTrackings");
                });

            modelBuilder.Entity("LongevityDiet.Tracking.Domain.Entities.MealTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DailyTrackingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealPlanItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanItemId");

                    b.HasIndex("DailyTrackingId", "MealPlanItemId")
                        .IsUnique();

                    b.ToTable("MealTrackings");
                });

            modelBuilder.Entity("LongevityDiet.Tracking.Domain.Entities.ProgressSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedMeals")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LastNotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastNotificationSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<int>("PlannedMeals")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PeriodStartDate", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("ProgressSummaries");
                });

            modelBuilder.Entity("LongevityDiet.Tracking.Domain.Entities.MealTracking", b =>
                {
                    b.HasOne("LongevityDiet.Tracking.Domain.Entities.DailyTracking", "DailyTracking")
                        .WithMany("Meals")
                        .HasForeignKey("DailyTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyTracking");
                });

            modelBuilder.Entity("LongevityDiet.Tracking.Domain.Entities.DailyTracking", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
