<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\Notification\LongevityDiet.Notification.Grpc\Protos\notification.proto" GrpcServices="Client" Link="Protos\notification.proto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LongevityDiet.Tracking.Application\LongevityDiet.Tracking.Application.csproj" />
    <ProjectReference Include="..\LongevityDiet.Tracking.Domain\LongevityDiet.Tracking.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
